### ISSUE TITLE
Adding more examples & one more library

### ISSUE THREAD

**Issue by Quoteme** [ubavic/awesome-interactive-math#1]
I love this project, thanks for starting it. In case I can interest you, there are many mathematical texts with interactive visualizations on my website (completely FOSS: https://quoteme.github.io/projects). Some highlights are  [top2man, an interactive visualization of all topological compact, non-empty, real 2 manifolds](https://quoteme.github.io/top2man/),  [a visual explanation of e^it = cos(t)+isin(t)](https://quoteme.github.io/math/powerseries_sin.html), and [my seminar on rational points  on elliptic curves](https://quoteme.github.io/rpoec/presentation/#/Erinnerung)

Some tool I used which might be of interest and which were not mentioned before is sage-math with its awesome [to-THREE.js export function](https://doc.sagemath.org/html/en/reference/plot3d/threejs.html). This allows for much more powerful 3d-plots. Also [impress.js](https://impress.js.org/#/bored) is nice to have

**Comment by ubavic** [comment]
Thank you for recommendation. 
I sent mail to your `gmx.de` address with some suggestions.
