### ISSUE TITLE
Please update the Primer on Bezier entry to be by "Pomax" rather than using my legal name

### ISSUE THREAD

**Issue by Pomax** [ubavic/awesome-interactive-math#7]
Hiya, 

The Primer on Bezier curves is currently attributed to my legal name, rather than my real name - could that please be changed to say "Pomax"? Virtually no one knows me by my legal name, and I like to keep it that way =)

(It's only in the footer signature for legal reasons)

**Comment by ubavic** [comment]
Fixed. 
I cleaned git history, so from now on your name will not appear in it.  However, you should ask other persons to delete their respective forks. If you want, I could do it for you.

When you read this message, feel free to close this issue and I will delete it, for extra protection. If there is a need, we can continue the conversation over mail. 

Sorry for the caused inconvenience.

**Comment by Pomax** [comment]
no need to delete, it's not "secret" information, more a matter of correct attribution. I have asked the only fork that has click-throughs to the primer to update their file as well, so with the master updated and their fork (hopefully) updated as well, things should be fine.
