### ISSUE TITLE
DOM-diff

### ISSUE THREAD

**Issue by TWINGSISTER** [ubavic/awesome-interactive-math#8]
Someone https://github.com/marcelklehr quoted DOM-diff that is no longer within your repos (am I wrong?). I am trying to build a support for history  in Geogebra  (to give some evidence whenever you use GGB in activities with auto grading in Moodle). GGB stores its internal status in a large XML and snapshotting it at every student's step  to get some evidence, for all the students in all classes for the whole school year, will sink Moodle MySQL DB. At every step few things changes so storing DOM diffs will be a game changer. When some evidence/explanation  is required for a bad note teacher will show the  history  created applying deltas and showing the student's process. Surprisingly Stackoverflow do not contain any hint for diff-ing XMLs. Obviously I can utter a  bunch of recursive js lines that can do the job but I do not like to reinvent the wheel. To fit in GGB Javascript it must be a single file js. Can you help?

**Comment by ubavic** [comment]
I think that you mistook me for someone else. I would like to help you, but I never did anything similar.
